apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8s-deployment
spec:
  selector:
    matchLabels:
    app: spring-boot-k8s
    replicas: 2
    template:
    metadata:
      labels:
        spec:
        containers:
         - name: spring-boot-k8s
           image: hellowordapplication
           imagePullPolicy: IfNotPresent
           ports:
            - containerPort: 8070
            
---
    
apiVersion: v1
kind: Service
metadata:
  name: springboot-k8ssvc
  spec:
    selector:
     app: spring-boot-k8s
  ports: 
    - protocol: "TCP"
      port: 8070
      targetport: 8070
      type: NodePort
      

            
            
        
